### ISSUE TITLE
Could not cast value of type 'SwiftSyntax.UnknownSyntax' to 'SwiftSyntax.FunctionCallArgumentListSyntax'

### ISSUE THREAD

**Issue by imairi** [grab/swift-leak-check#1]
Check the below class by SwiftLeakChecker command line tool, the cast error is occurred and checker operation is stopped.

## Sample codes

```
import Foundation
import UIKit

final class Test {
    let message = "Hello!"

    func showMessage() {
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) {
            print(self.message)
        }
    }
}
```

## Run 

```
SwiftLeakChecker path/to/File.swift
```

SwiftLeakChecker is the latest version.

```
  swift-leak-check
    - 1.2.1 (SwiftLeakChecker) *
```

## Error
```
Could not cast value of type 'SwiftSyntax.UnknownSyntax' (0x10b399200) to 'SwiftSyntax.FunctionCallArgumentListSyntax' (0x10b393378).
Abort trap: 6
```

## Expected result

The result is expected to show the line like the below.

```
  `self` is strongly captured at (line: 9, column: 18), 
```

**Comment by imairi** [comment]
It is because SwiftLeakChecker may use old swift-syntax version.
My environment is Swift 5.2.

**Comment by namanhams** [comment]
@imairi : thanks for reporting this and sorry for the slow response. We will check on this.

**Comment by namanhams** [comment]
@imairi : we have fixed the issue. You can checkout the latest from master branch. The issue was indeed due to changes in Swift 5 compiler. Thanks for spotting this.

**Comment by imairi** [comment]
@namanhams Thanks for fixing the issue. I checked the behavior in my environment. LGTM ❤️

**Comment by imairi** [comment]
@namanhams 

I found the unnecessary debug log for results.
Please check it. https://github.com/grab/swift-leak-check/pull/2
