### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by lekhanhtoan37** [grab/swift-leak-check#3]
I got error when compile SwiftLeakChecker target
`dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /Users/mac/Library/Developer/Xcode/DerivedData/swift-leak-check-engenlgczlupencadwxezfhvupfr/Build/Products/Debug/SwiftLeakChecker
  Reason: image not found
(lldb) `
I built with:
- Xcode 12.5
- Swift 5.4

**Comment by lekhanhtoan37** [comment]
I tried to fall back on Xcode 11.5 and still get this error

**Comment by lekhanhtoan37** [comment]
Solved by:
- Changing directory of SwiftSyntax build folder.
`module _CSwiftSyntax {
    umbrella "/Users/hoang.le/Projects/SwiftLeakCheck/.build/checkouts/swift-syntax/Sources/_CSwiftSyntax/include"
    export *
}`
- Update SwiftSyntax to 0.50400 for compatible with Swift 5.4

**Comment by 405092901** [comment]
> * 0.50400 for compatible with Swift 5

why my project is error? the error message is 
/..../swift-leak-check-master/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:120:46: Value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'

**Comment by 405092901** [comment]
> Solved by:
> 
> * Changing directory of SwiftSyntax build folder.
>   `module _CSwiftSyntax { umbrella "/Users/hoang.le/Projects/SwiftLeakCheck/.build/checkouts/swift-syntax/Sources/_CSwiftSyntax/include" export * }`
> * Update SwiftSyntax to 0.50400 for compatible with Swift 5.4

Could you forward your build project to my email?  405092901#qq.com
